### ISSUE TITLE
Error with sbt-jshint

### ISSUE THREAD

**Issue by guersam** [vmunier/play-with-scalajs-example#29]
When [sbt-jshint](https://github.com/sbt/sbt-jshint) plugin is added, `jshint` task fails with the following error:
```
[info] Fast optimizing /home/guersam/study/play-with-scalajs-example/example-client/target/scala-2.11/exampleclient-fastopt.js
[info] JavaScript linting on 2 source(s)
[trace] Stack trace suppressed: run last exampleServer/web-assets:jshint for the full output.
[error] (exampleServer/web-assets:jshint) No mapping for /home/guersam/study/play-with-scalajs-example/example-client/target/scala-2.11/exampleclient-fastopt.js
[error] application - 

! @6l7obo21d - Internal server error, for (GET) [/] ->

play.PlayExceptions$UnexpectedException: Unexpected exception[RuntimeException: No mapping for /home/guersam/study/play-with-scalajs-example/example-client/target/scala-2.11/exampleclient-fastopt.js]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:237) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.5.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
Caused by: java.lang.RuntimeException: No mapping for /home/guersam/study/play-with-scalajs-example/example-client/target/scala-2.11/exampleclient-fastopt.js
	at scala.sys.package$.error(package.scala:27) ~[scala-library-2.11.5.jar:na]
	at sbt.Mapper$$anonfun$fail$1.apply(PathMapper.scala:37) ~[na:na]
	at sbt.Mapper$$anonfun$fail$1.apply(PathMapper.scala:37) ~[na:na]
	at sbt.Alternatives$$anon$1$$anonfun$$bar$1$$anonfun$apply$3.apply(PathMapper.scala:117) ~[na:na]
	at sbt.Alternatives$$anon$1$$anonfun$$bar$1$$anonfun$apply$3.apply(PathMapper.scala:117) ~[na:na]
```

Although it's unusual to have jshint with scala-js, It's annoying when it happens.

**Comment by vmunier** [comment]
Hi @guersam,

You can use `excludeFilter in JshintKeys.jshint := "*-fastopt.js" || "*-launcher.js"` in the Play settings. JSHint won't be run on Scala.js output and you won't get that error message.

**Comment by vmunier** [comment]
Hi @guersam, if you upgrade to `sbt-play-scalajs` v0.2.2, the Scala.js output will not be used by `jshint` anymore. So you won't get this error anymore and you don't need to use `excludeFilter`.

**Comment by guersam** [comment]
Awesome, thanks a lot!
