### ISSUE TITLE
(run-main-1) java.lang.ClassNotFoundException: example.ExampleJS Error when run in activator 

### ISSUE THREAD

**Issue by cloudarch** [vmunier/play-with-scalajs-example#35]
Hi,

I downloaded the project, compiled it in Activator UI and when I try to run it I hit the error below. I also tried to run the activator template and hit the same error. 

 
(run-main-1) java.lang.ClassNotFoundException: example.ExampleJS
example.ExampleJS

Exception in thread "sbt-bg-threads-3" java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:1938)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:1938)
	at scala.Option.foreach(Option.scala:236)
	at sbt.BuildCommon$class.toError(Defaults.scala:1938)
	at sbt.package$.toError(package.scala:4)
	at sbt.plugins.BackgroundRun$$$$b4c18989468ecd5aa4b4422d7494c6$$$$onfun$apply$6.apply(BackgroundRunPlugin.scala:38)
	at sbt.plugins.BackgroundRun$$$$b4c18989468ecd5aa4b4422d7494c6$$$$onfun$apply$6.apply(BackgroundRunPlugin.scala:37)
	at sbt.BackgroundThreadPool$$anonfun$1.apply$mcV$sp(AbstractBackgroundJobService.scala:134)
	at sbt.BackgroundThreadPool$BackgroundRunnable.run(AbstractBackgroundJobService.scala:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

**Comment by cloudarch** [comment]
When run from Activator console vs UI everything works great. Closing the issue.
