### ISSUE TITLE
SBT setup not compatible with (Scala.js) jQuery bindings?

### ISSUE THREAD

**Issue by sebnozzi** [vmunier/play-with-scalajs-example#39]
When I add the scalajs-jquery dependency for the client, like this:

```scala
lazy val client = (project in file("client")).settings(
  scalaVersion := scalaV,
  persistLauncher := true,
  persistLauncher in Test := false,
  libraryDependencies ++= Seq(
    "org.scala-js" %%% "scalajs-dom" % "0.8.0",
    "com.lihaoyi" %%% "upickle" % "0.3.6",
    "be.doeraene" %%% "scalajs-jquery" % "0.8.0"
  )
).enablePlugins(ScalaJSPlugin, ScalaJSPlay).
  dependsOn(sharedJs)
```

When I load the Play page I get this exception:

```
! @6ng342o0l - Internal server error, for (GET) [/] ->

play.sbt.PlayExceptions$UnexpectedException: Unexpected exception[JSLibResolveException: Some references to JS libraries could not be resolved:
- Ambiguous reference to a JS library: jquery.js
  Possible paths found on the classpath:
  - scala/tools/nsc/doc/html/resource/lib/jquery.js
  - META-INF/resources/webjars/jquery/2.1.3/jquery.js
  originating from: root:compile
]
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:51) ~[na:na]
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.7.jar:na]
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44) ~[na:na]
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40) ~[na:na]
	at play.sbt.run.PlayReload$$anonfun$compile$2$$anonfun$apply$3.apply(PlayReload.scala:20) ~[na:na]
	at play.sbt.run.PlayReload$$anonfun$compile$2$$anonfun$apply$3.apply(PlayReload.scala:20) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.7.jar:na]
	at play.sbt.run.PlayReload$$anonfun$compile$2.apply(PlayReload.scala:20) ~[na:na]
	at play.sbt.run.PlayReload$$anonfun$compile$2.apply(PlayReload.scala:18) ~[na:na]
Caused by: org.scalajs.core.tools.classpath.JSLibResolveException: Some references to JS libraries could not be resolved:
- Ambiguous reference to a JS library: jquery.js
  Possible paths found on the classpath:
  - scala/tools/nsc/doc/html/resource/lib/jquery.js
  - META-INF/resources/webjars/jquery/2.1.3/jquery.js
  originating from: root:compile

	at org.scalajs.core.tools.classpath.PartialClasspath.resolveAllResourceNames(PartialClasspath.scala:137) ~[na:na]
	at org.scalajs.core.tools.classpath.PartialClasspath.resolveDependencies(PartialClasspath.scala:80) ~[na:na]
	at org.scalajs.core.tools.classpath.PartialClasspath.resolve(PartialClasspath.scala:64) ~[na:na]
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$16.apply(ScalaJSPluginInternal.scala:220) ~[na:na]
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$16.apply(ScalaJSPluginInternal.scala:217) ~[na:na]
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47) ~[scala-library-2.11.7.jar:na]
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40) ~[na:na]
	at sbt.std.Transform$$anon$4.work(System.scala:63) ~[na:na]
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226) ~[na:na]
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226) ~[na:na]
```

Out-commenting the "webjars" dependency for the "server" does not solve the issue:

```
    // "org.webjars" % "jquery" % "1.11.1",
```

This is probably not an issue with this setup itself, but due to my ignorance of how to deal with this problem.

**Comment by sebnozzi** [comment]
Maybe related to this...?

https://github.com/scala-js/scala-js-jquery/issues/22

**Comment by vmunier** [comment]
That's strange but it looks like the issue comes from the `sbt-heroku` plugin.
Try removing `sbt-heroku` from `project/plugins.sbt` and remove heroku specific lines from `build.sbt`.

**Comment by sebnozzi** [comment]
Will try that, thanks.
>
>

**Comment by sebnozzi** [comment]
After removing the Heroku plugin and SBT settings it works indeed.

**Comment by vmunier** [comment]
`sbt-heroku` v0.5.3.1 fixes the issue.
https://github.com/vmunier/play-with-scalajs-example/commit/77c73aca1173b2728a9e195cd4b4ef945a8f96f0
https://github.com/heroku/sbt-heroku/issues/24
